### ISSUE TITLE
"Random" segmentation faults on memory deallocations

### ISSUE THREAD

**Issue by alexcristd** [wang-bin/mdk-sdk#64]
Hello,

Using Qt5 with MinGW 8.1.0 64bit on Windows 10 64bit, and MDK 0.15.0.

I'm experiencing in my app seemingly random SIGSEGV exceptions in MDK libraries after prepare requests. This can happen sooner or later, after just a couple prepares, or after multiple ones.
_Context: my app uses a scenario similar to PlaylistAsOne, and the user can seek through multiple files by single clicks or continuously dragging over a progress bar (which may lead to very fast file changes). The crash can appear after just a couple clicks, or after multiple different seeks (not necessarily quick seeks, they can be spread over multiple minutes, and can be caused by single seeks, not by drags/quick file changes)._

I can't find a reliable way to reproduce it 100%.

But I attached an archive with a stress scenario that quickly prepares/sets next media (not sure if it matters, but it's what my app does)/starts playback. Sooner or later, one or more HEAP deallocation errors may or may not appear (they usually do, but sometimes it crashes without them):
![image](https://user-images.githubusercontent.com/49856105/176989517-6f621cc0-4bee-4fef-9a14-45a48c38913e.png)

Then everything ends with SIGSEGV:
![image](https://user-images.githubusercontent.com/49856105/176989529-2cd8cb76-0e3c-4db7-9e50-11d945b314e8.png)

This is the sample code: https://drive.google.com/file/d/1zBrYRb1jptY7aG78TwKttdYTWF0gidkV/view?usp=sharing
I've noticed this happening with MP4 files, but I don't think the filetype matters. Anyway, the archive contains one sample video (the code switches between 2 files, you can just copy it).

**NOTE: _Sometimes_ it just works. If it doesn't seem to crash, just stop it, wait a few minutes and try again.** It seems random, but it happens very often.

**Comment by wang-bin** [comment]
thanks for your example, it should be fixed in the latest build. tested on mac.

**Comment by alexcristd** [comment]
I tested the today's version ("mdk-sdk-windows-desktop.7z",  2022-07-03 12:28:29 UTC). The HEAP errors seem to be fixed, or at least they didn't appear anymore.

However, SIGSEGV is still present, using the same sample code on Windows:

![image](https://user-images.githubusercontent.com/49856105/177055807-7615b487-9ff9-4de2-923f-e3e8d1ef9df6.png)

Tested a few times, all crashed after about 80-120 steps.

**Comment by wang-bin** [comment]
this crash is in the log, it's a know bug, i don't know the reason yet. You can simply disable the log, no setLogHandler

**Comment by wang-bin** [comment]
try the latest build

**Comment by wang-bin** [comment]
crash in log should be fixed in the latest release
